### ISSUE TITLE
Package wont install

### ISSUE THREAD

**Issue by RJHendricks22** [wojtkowiak/electron-windows-osk#1]
Getting errors and then the folder simply deletes itself after fails installation.  Here's errors:
> electron-windows-osk@1.0.14 install ... node_modules/electron-windows-osk
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/addon/main.o
../main.cpp:3:10: fatal error: 'ShlObj.h' file not found
#include <ShlObj.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/addon/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/USER/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/USER/.nvm/versions/node/v7.6.0/lib/node_modules/node/lib/node_modules/node/bin/node" "/Users/USER/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/USER/code/communico_tools/platform_final/platform/node_modules/electron-windows-osk
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by wojtkowiak** [comment]
Are you using `windows-build-tools`? 
It seems that sth is wrong with compiling it on your machine. 
Not really sure if the fault is in the package.
You can google for `fatal error: 'ShlObj.h' file not found`, there are several other issues on github from different projects where people did solve it.

**Comment by RJHendricks22** [comment]
Yep you're right, the error messages from the build tools led me to believe things were missing from the package but i was wrong.  Thank you for the reply
